COLUMNS:



Area                 :  object 
Item                : object 
Year              : int64  
hg/ha_yield     :  int64  
average_rain_fall_mm_per_year  : float64
pesticides_tonnes             :  float64
avg_temp                   :  float64



TARGET_COLUMN:
  name:  hg/ha_yield 
